server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 333

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.scnu.springcloud.entities