server:
  port: 90

spring:
  application:
    name: cloudalibaba-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:1111  #linux下nacos集群
    sentinel:
      transport:
        dashboard: localhost:8080  #控制台的地址
        port: 8719 #默认端口,被占用的话开始依次+1扫描

management:
  endpoints:
    web:
      exposure:
        include: '*'


service-url:
  provider-payment: http://nacos-payment-provider

feign:
  sentinel:
    enabled: true