server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh                 #路由的id,没有固定要求,建议配合服务名
          #uri: http://localhost:8001       #匹配后提供的服务地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #lb://serverName 是springCloud gateway 在微服务中自动为我们创建的负载均衡
          predicates:
            - Path=/payment/**    #断言,路径相匹配的进行路由
            #- After=2021-08-22T14:16:31.475+08:00[Asia/Shanghai]  #ZonedDateTime
            #- Before=2021-08-22T12:16:31.475+08:00[Asia/Shanghai]
            #- Between=2021-08-22T12:16:31.475+08:00[Asia/Shanghai],2021-08-22T14:16:31.475+08:00[Asia/Shanghai]
            #- Cookie=username,xhy # curl http://localhost:9527/payment/lb --cookie "username=xhy"
            #- Header=X-request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式 -> curl http://localhost:9527/payment/lb -H "X-request-Id:2"
            #- Query=auth,token  #curl http://localhost:9527/payment/lb?auth=token

