server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:1111  #linux下nacos集群
    sentinel:
      transport:
        dashboard: localhost:8080  #控制台的地址
        port: 8719 #默认端口,被占用的话开始依次+1扫描
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.200.130:1111
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
