server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#用于服务降级,在注解@FeignClient中添加fallback属性值
feign:
  hystrix:
    enabled: true

